### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by baggepinnen** [brianguenter/FastDifferentiation.jl#13]
Hello and thanks for this interesting package! I have been exploring a bit and ran into a couple of issues, the biggest one being that I cannot get `sparse_hessian` below to work. Some other issues I ran into while trying are indicated with `# Error` below.
```julia
using FastDifferentiation

x = make_variables(:x, 2)
mu = make_variables(:mu, 2)

# x'mu          # Error
# dot(x, mu)    # Error
ex = sum(abs2, x .* mu)

h = sparse_hessian(ex, x)
# hs = sparse_hessian(ex, x) # Error

# fun = make_function(h, x, mu) # Error (it would be nice if functions could take more than one argument)
fun = make_function(h, [x; mu])
```

**Comment by brianguenter** [comment]
Found the errors. When you create a hessian the code currently requires you to list all the variables of the function. 

if you change
```
h = sparse_hessian(ex, x)
```
to this
```
h = sparse_hessian(ex, [x;mu])
```
it works. The code requires you to list all the variables of the function when taking the hessian. I don't think this would be hard to change - is it common to want to compute second partials just wrt to a subset of the variables?

this doesn't work
```
x'mu
```
because I didn't define Base.adjoint for the Node type. It works with that mode.

**Comment by brianguenter** [comment]
I fixed the adjoint bug and made a new release 0.2.1. If you grab that `x'mu` should work. Still looking at the hessian issue.

**Comment by brianguenter** [comment]
fixed the sparse hessian so it behaves the same as hessian when taking derivatives wrt just some of the variables of the function.

**Comment by baggepinnen** [comment]
> is it common to want to compute second partials just wrt to a subset of the variables?

Yes, here are a few use cases
- Construct Hessian of Lagrangian for optimization using, e.g., Ipopt, that wants the function $\dfrac{d^2}{dx^2}(\sigma f(x) + \mu^T c(x))$ but $\sigma, \mu$ are still arguments to the function.
- SciML functions all have a parameter vector which the user can supply, and crucially, change at any time. It must therefore be an argument to any code generated so as to not have to re-generate the derivative code if the parameter vector is changed. For example, to compute the jacobian $\dfrac{d}{dx} f(x, p, t)$ where $f$ is the dynamics RHS of an ODE.

**Comment by brianguenter** [comment]
Thanks for the information about the use cases. The dense hessian already supported this - I made a new v0.2.2 which has a fix so sparse_hessian does as well. Try it and let me know if it works for you.. 

All of your bugs are fixed in v0.2.2 except for dot(x,y). Still working on that one, dot is doing something weird which I haven't figured out yet.

**Comment by baggepinnen** [comment]
Thanks for your quick fixes!

>  The dense hessian already supported this - I made a new v0.2.2 which has a fix so sparse_hessian does as well. Try it and let me know if it works for you..

I can't quite seem to get it to work. This is on `FastDifferentiation#main`:
```julia
using FastDifferentiation
x = make_variables(:x, 2)
mu = make_variables(:mu, 2)
ex = sum(abs2, x .* mu)
h = sparse_hessian(ex, x)
fun = make_function(h, x, mu)
```

```julia
julia> fun = make_function(h, x, mu)
ERROR: MethodError: no method matching make_function(::SparseArrays.SparseMatrixCSC{FastDifferentiation.Node, Int64}, ::Vector{FastDifferentiation.Node}, ::Vector{FastDifferentiation.Node})

Closest candidates are:
  make_function(::AbstractArray{T}, ::AbstractVector{S}; in_place) where {T<:FastDifferentiation.Node, S<:FastDifferentiation.Node}
   @ FastDifferentiation ~/.julia/packages/FastDifferentiation/Ays9i/src/CodeGeneration.jl:85

Stacktrace:
 [1] top-level scope
   @ REPL[21]:1
```

**Comment by brianguenter** [comment]
There is a newer release which has all the fixes but Tagbot is flaking out, crashing and not installing the latest  version. I'll work on it tomorrow.

**Comment by baggepinnen** [comment]
> When possible I make argument types explicit, as a form of documentation to the user. This is especially handy when using VSCode where intellisense hover shows the function signature.

In Julia. typed input arguments are not intended for documentation, they are for dispatch. vscode shows the docstring as well, so you could indicate one signature in the docstring but actually implement a less restrictive signature in the code. 

> But this only works if the element type of all the vecargs is the same. 

This is probably okay for most use cases, but the restriction is kind of artificial so it feels unnecessary. 

> But then the user is left guessing what the element type of the vectors in vecargs should be.

The proper way to write this is 
```julia
make_function(h::SparseMatrixCSC{T}, vecargs::AbstractVector{<: Node}...; in_place=true) where {T<:Node,S<:Node} = "worked"
```
the key point is the `<:` in `AbstractVector{<: Node}`

> But then the user is left guessing what the element type of the vectors in vecargs should be.

Not if you say what the element type is expected to be in the docstring. For example, the docstring signature can be 
```julia
make_function(::SparseMatrixCSC{T}, ::Vector{Node}...; in_place)
```
while the actual implementation is 
```julia
make_function(::SparseMatrixCSC{T}, ::AbstractVector{<:Node}...; in_place)
```

**Comment by brianguenter** [comment]
You can now pass in a list of vectors for input variables.

**Comment by brianguenter** [comment]
if you don't find any other problems I'll close this issue in a day or two.

**Comment by brianguenter** [comment]
Haven't heard anything so closing this issue.

**Comment by baggepinnen** [comment]
Sorry for taking a while to get back to this. On the latest released version, I tried to create a function of several arguments, but it does not appear to work:
```julia
using FastDifferentiation

x = make_variables(:x, 2)
mu = make_variables(:mu, 2)
ex = sum(abs2, x .* mu)
hs = sparse_hessian(ex, x)
fun = make_function(hs, x, mu; in_place=false)
# Test
xv = randn(size(x))
muv = randn(size(mu))
fun(xv, muv)
```

If we inspect the expression of the generated function, it sill has a single argument only:
```julia
julia> fun
RuntimeGeneratedFunction(#=in FastDifferentiation=#, #=using FastDifferentiation=#, :((input_variables,)->begin
          #= /home/fredrikb/.julia/packages/FastDifferentiation/vh3e2/src/CodeGeneration.jl:133 =#
          begin
```
