### ISSUE TITLE
Promotion issue

### ISSUE THREAD

**Issue by baggepinnen** [brianguenter/FastDifferentiation.jl#19]
I just ran into this issue 
```julia
ERROR: promotion of types FastDifferentiation.Node{typeof(*), 2} and FastDifferentiation.Node{Float64, 0} failed to change any arguments
Stacktrace:
  [1] error(::String, ::String, ::String)
    @ Base ./error.jl:44
  [2] sametype_error(input::Tuple{FastDifferentiation.Node{typeof(*), 2}, FastDifferentiation.Node{Float64, 0}})
    @ Base ./promotion.jl:405
  [3] not_sametype(x::Tuple{FastDifferentiation.Node{typeof(*), 2}, FastDifferentiation.Node{Float64, 0}}, y::Tuple{FastDifferentiation.Node{typeof(*), 2}, FastDifferentiation.Node{Float64, 0}})
    @ Base ./promotion.jl:399
  [4] promote
    @ ./promotion.jl:382 [inlined]
  [5] mul_fast(::FastDifferentiation.Node{typeof(*), 2}, ::FastDifferentiation.Node{Float64, 0})
    @ Base.FastMath ./fastmath.jl:267
  [6] mul_fast(::FastDifferentiation.Node{typeof(*), 2}, ::Float64)
    @ Base.FastMath ./fastmath.jl:267
```

I can work on an MWE if that would be helpful, but I think that the error message might be detailed enough to figure out what promotion is missing

**Comment by brianguenter** [comment]
A MWE would help so I can ensure your bug is fixed. Otherwise I might be fixing a similar but not identical bug. 

Keep the bug reports coming. It helps me fix the code.

**Comment by brianguenter** [comment]
A MWE will be a necessity I think. This is not a promotion error on Node types, it's an error on promotion of Tuples of Nodes. Not clear to me when this would arise. If you have an MWE that will be helpful.

**Comment by brianguenter** [comment]
If you can't make a MWE I'll close this issue. Open a new issue if it happens again.

**Comment by brianguenter** [comment]
@baggepinnen I you have time to make a MWE I'll fix this bug. Otherwise I'll close the issue.

**Comment by baggepinnen** [comment]
I will try, I used our MPC library with lots of generated code so it might take a while

**Comment by brianguenter** [comment]
Thank you. I really appreciate your bug reports. They are super helpful in making the code more reliable.

**Comment by brianguenter** [comment]
@baggepinnen if you don't have time to make a MWE I'll close this issue. You can reopen it if it comes up again.
