### ISSUE TITLE
Support for conditionals

### ISSUE THREAD

**Issue by lassepe** [brianguenter/FastDifferentiation.jl#35]
Thank you for this great package! It looks really exciting! From my initial testing, I am intrigued by the reduced code-generation and compilation times compared Symbolics.jl

Disclaimer: I am aware that this limitation is [documented](https://brianguenter.github.io/FastDifferentiation.jl/dev/limitations/). I am opening this issue to figure out how far we are from the [long-term solution](https://brianguenter.github.io/FastDifferentiation.jl/dev/futurework/#Future-Work) and to hash out opportunities for potential intermediate solutions.

The main thing that currently prevents me from using FastDifferentation.jl in my use-cases is that a lot of my code requires `ifelse(x::Node <= y::Node, f(x), g(x))` to work. In these settings, `y` takes the role of a threshold that the user can select at runtime. (i.e., the result at each branch does not depend on `y`). For rare use of such conditions, duplication of the graph (as proposed in #11)  seems like a useful (despite suboptimal) intermediate solution. Would it be possible to add such a rule before the [JIT branch](https://github.com/brianguenter/FastDifferentiation.jl/tree/Jit) has landed?

**Comment by brianguenter** [comment]
It's clear that many users need at least basic support for conditionals. It's my next task. I'll have a better feel for how long this might take in a couple of weeks after I get the basic code in place and can see how difficult making it fully functional will be.

**Comment by brianguenter** [comment]
I'm going to convert this to a discussion, since it's not really an issue. Feel free to continue posting the new discussion item.

**Comment by brianguenter** [comment]
I'm closing this issue because I've opened another with the same topic https://github.com/brianguenter/FastDifferentiation.jl/issues/89#issue-2442985806
