### ISSUE TITLE
`make_function` with multiple arguments gives incorrect results

### ISSUE THREAD

**Issue by lassepe** [brianguenter/FastDifferentiation.jl#36]
The docstring of `make_function` suggests, that the function can have multiple arguments.

```julia
make_function(func_array::AbstractArray{T}, input_variables::AbstractVector{<:Node}...; in_place::Bool=false, init_with_zeros::Bool=true) where {T<:Node}
```

However, multi-argument functions lead to some unexpected results:

**Example 1**

In the out-of-place version, I get wrong results for outputs that depend on the second argument:

```julia
using FastDifferentiation: FastDifferentiation as FD

function main()
    f = let
        x = FD.make_variables(:x, 5)
        y = FD.make_variables(:y, 5)
        f = [sum(x), sum(y)]
        FD.make_function(f, x, y)
    end

    x = rand(5)
    y = rand(5)

    @show sum(x)
    @show sum(y)

    f(x, y)
end
```

Output:

```julia
julia> main()
sum(x) = 2.751503839962046
sum(y) = 2.9154113018482892
2-element Vector{Float64}:
 2.751503839962046
 1.3860504967202e-309
```

**Example 2**

In the in-place version, the result is not filled. It looks like the *second* argument (y) is treated as the result, not the last argument

```julia
using FastDifferentiation: FastDifferentiation as FD

function main()
    f! = let
        x = FD.make_variables(:x, 5)
        y = FD.make_variables(:y, 5)
        f = [sum(x), sum(y)]
        FD.make_function(f, x, y; in_place=true)
    end

    result = zeros(2)
    x = rand(5)
    y = rand(5)

    @show sum(x)
    @show sum(y)

    f!(x, y, result)

    (; result, x, y)
end
```

Output:

```julia
julia> main()
sum(x) = 3.319041139723611
sum(y) = 3.1858101463166837
(result = [0.0, 0.0], x = [0.69018293692345, 0.6121067491599018, 0.42652081744165704, 0.772458258313714, 0.8177723778848882], y = [3.319041139723611, 0.0, 0.0, 0.0, 0.0])
```

---

Side note: As part of a potential fix for in-place case above, it may be worth considering to make `result` (the mutated variable) the first positional argument to align with the general style guide; cf. point 3 in [this list in the manual](https://docs.julialang.org/en/v1/manual/style-guide/#Write-functions-with-argument-ordering-similar-to-Julia-Base)

**Comment by brianguenter** [comment]
The documentation needs to be changed. You can pass multiple input variable vectors to `make_function` but the function it creates takes a single vector argument which is the concatenation of these vectors. Example:

```
function main()
    f! = let
        x = FD.make_variables(:x, 5)
        y = FD.make_variables(:y, 5)
        f = [sum(x), sum(y)]
        FD.make_function(f, x, y; in_place=true)
    end

    result = zeros(2)
    x = rand(5)
    y = rand(5)


    @show sum(x)
    @show sum(y)

    f!([x; y], result) #NOTICE concatenation of input vectors.

    (; result, x, y)
end
```

Executing main:
```
julia> main()
sum(x) = 1.5177597666965652
sum(y) = 2.884056822058924
(result = [1.5177597666965652, 2.884056822058924], x = [0.03756393173261685, 0.2740090491608269, 0.23931033453489958, 0.04935397579571965, 0.9175224754725023], y = [0.011279086138370809, 0.7658719184104853, 0.9879329862968057, 0.6513599913049349, 0.4676128399083279])
```

I could change `make_function` to generate a function that would take multiple input vector arguments, which would be a breaking change, or change the documentation to clarify what is going on. My inclination is to do the former; it's conceptually simpler. And to put the argument being modified first, which is also a breaking change. Let me think about it for a day or two.
