### ISSUE TITLE
Can't use norm() from LinearAlgebra

### ISSUE THREAD

**Issue by ejmeitz** [brianguenter/FastDifferentiation.jl#52]
I cannot seem to use `norm` in my functions, but I can just write `sqrt(sum(x -> x^2,v))`. Would it be too hard to support `norm` (like how cos, sin are supported)?

**Comment by brianguenter** [comment]
**FD** uses DiffRules.jl, which doesn't appear to have a definition for norm. One difficulty with supporting norm directly: it would be an n-ary operator. There are only unary and binary operations now - adding n-ary will almost certainly break things.

There's a long list of high priority items that will come before this so it could be a while before it gets done, assuming it wouldn't cause cascading changes that make it a lot of work. Until then I'd recommend defining your own norm function as you described.

**Comment by brianguenter** [comment]
I'm going to close this issue since it will be months, at least, before I could look at it, assuming it made sense to do. If it pops up again as a sore point after the high priority items are done then I'll reconsider it.
