### ISSUE TITLE
Support for `derivative(FastDifferenation.Node)`

### ISSUE THREAD

**Issue by ejmeitz** [brianguenter/FastDifferentiation.jl#56]
Would it be possible to add an overload for `derivative(FastDifferneiation.Node,...)` so you don't need to make your input an array?

**Comment by brianguenter** [comment]
just pushed to the Julia registry. should be live in 15-20 minutes.

**Comment by ejmeitz** [comment]
Thanks!

**Comment by ejmeitz** [comment]
I don't think this patch worked btw, I still get:
` BoundsError: attempt to access 1-element Vector{FastDifferentiation.PathEdge{Int64}} at index [0]`
if I don't put the input in [].

Here's the top of the stack trace:

> Stacktrace:
>       [1] _deleteend!
>         @ .\array.jl:1023 [inlined]
>       [2] empty!
>         @ .\array.jl:1773 [inlined]
>       [3] get_edge_vector()
>         @ FastDifferentiation C:\Users\ejmei\.julia\packages\FastDifferentiation\mftkg\src\Factoring.jl:269
>       [4] old_edge_path(next_node_constraint::FastDifferentiation.PathConstraint{Int64}, dominating::Int64, is_dominator::Bool, reachable_mask::BitVector, current_edge::FastDifferentiation.PathEdge{Int64, 9, 1})
>         @ FastDifferentiation C:\Users\ejmei\.julia\packages\FastDifferentiation\mftkg\src\Factoring.jl:299
>       [5] evaluate_subgraph(subgraph::FastDifferentiation.FactorableSubgraph{Int64, FastDifferentiation.DominatorSubgraph})

**Comment by ejmeitz** [comment]
Ah that makes sense, thanks! This makes me want to figure out a way to save the functions even more now.
