### ISSUE TITLE
Yank version 0.4.0?

### ISSUE THREAD

**Issue by moble** [brianguenter/FastDifferentiation.jl#92]
In #91, @brianguenter said

> nobody should be using 0.4.0.

Sounds very broken.  Should it be [yanked](https://github.com/JuliaRegistries/General/tree/master?tab=readme-ov-file#when-is-yanking-a-release-appropriate), then?  I believe it just involves adding `yanked = true` as line 90 of [this file](https://github.com/JuliaRegistries/General/blob/788524e49fc274b43ca4d7930cef10619171f08f/F/FastDifferentiation/Versions.toml#L89).

**Comment by brianguenter** [comment]
I asked on slack and the consensus was that I should instead issue a patch. There is a strong bias against yanking releases unless they contain major security issues, not just bugs. I'm going to issue a patch today, if I can find a few spare minutes to undo the changes and restore my repo to a sensible state.

**Comment by moble** [comment]
Ah, okay.  Thanks for the clarification!
